use_frameworks!

target 'KBScrollMagic_Example' do
  pod 'KBScrollMagic', :path => '../'
  
  pod 'VTMagic'
  pod 'SnapKit'
  pod 'MJRefresh'

  target 'KBScrollMagic_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
